# -*- coding: utf-8 -*-
"""企业微信渠道常量定义"""

# 消息类型
WECOM_MSGTYPE_TEXT = "text"
WECOM_MSGTYPE_IMAGE = "image"
WECOM_MSGTYPE_VOICE = "voice"
WECOM_MSGTYPE_FILE = "file"
WECOM_MSGTYPE_MIXED = "mixed"
WECOM_MSGTYPE_MARKDOWN = "markdown"
WECOM_MSGTYPE_STREAM = "stream"
WECOM_MSGTYPE_TEMPLATE_CARD = "template_card"

# 会话类型
WECOM_CHATTYPE_SINGLE = "single"
WECOM_CHATTYPE_GROUP = "group"

# 流式消息状态
WECOM_STREAM_STATUS_CONTINUE = 1
WECOM_STREAM_STATUS_END = 2
