# -*- coding: utf-8 -*-
"""企业微信渠道常量定义"""

# Token 过期时间（秒）
WECOM_ACCESS_TOKEN_TTL = 7200

# Token 提前刷新时间（秒）
WECOM_TOKEN_REFRESH_BEFORE_SECONDS = 300

# 媒体文件最大大小（字节）
WECOM_MEDIA_MAX_IMAGE_BYTES = 2 * 1024 * 1024  # 2MB
WECOM_MEDIA_MAX_FILE_BYTES = 20 * 1024 * 1024  # 20MB
WECOM_MEDIA_MAX_VOICE_BYTES = 2 * 1024 * 1024  # 2MB

# 消息去重缓存大小
WECOM_PROCESSED_IDS_MAX = 10000

# 昵称缓存大小
WECOM_NICKNAME_CACHE_MAX = 1000

# 用户信息获取超时（秒）
WECOM_USER_INFO_FETCH_TIMEOUT = 5

# 回调 URL 路径
WECOM_CALLBACK_PATH = "/wecom/callback"

# HTTP 服务器默认配置
WECOM_DEFAULT_HOST = "0.0.0.0"
WECOM_DEFAULT_PORT = 8765

# 流式消息状态
WECOM_STREAM_STATUS_CONTINUE = 1
WECOM_STREAM_STATUS_END = 2

# 消息类型
WECOM_MSGTYPE_TEXT = "text"
WECOM_MSGTYPE_IMAGE = "image"
WECOM_MSGTYPE_VOICE = "voice"
WECOM_MSGTYPE_FILE = "file"
WECOM_MSGTYPE_MIXED = "mixed"
WECOM_MSGTYPE_MARKDOWN = "markdown"
WECOM_MSGTYPE_STREAM = "stream"
WECOM_MSGTYPE_TEMPLATE_CARD = "template_card"

# 会话类型
WECOM_CHATTYPE_SINGLE = "single"
WECOM_CHATTYPE_GROUP = "group"
